services:
  go122:
    container_name: goadv
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgresql

  postgresql:
    container_name: goadv-db
    image: postgres:16.1
    ports:
      - "5432:5432"
    volumes:
      - ./.db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: goadv
      POSTGRES_PASSWORD: goadv
      POSTGRES_DB: goadv
